# Example configuration options that can be placed in your main SiriProxy config.yml

############################################
# NOTICE: Modifying these options in this 
#         file has no effect. You must put 
#         them in SiriProxy's ~/.siriproxy/config.yml
############################################

    - name: 'Horoscope' #don't touch
      path: 'git://github.com/rakusu/siriproxy-horoscope.git' #don't touch
